  version: '2'
  services:
    db:
      container_name: postgresdb
      image: postgres
      volumes:
        - sample_db:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=
        - POSTGRES_USER=postgres
        - POSTGRES_DB=tba-backend-db
      # - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - "5432:5432"
  volumes:
    productdb: {}